FROM node:18 AS builder

WORKDIR /build

COPY package.json yarn.lock ./

RUN yarn config set registry https://registry.npmmirror.com && yarn

COPY . .

RUN yarn build

FROM nginx:1.22 AS runner

WORKDIR /app

COPY --from=builder /build/dist dist

COPY --from=builder /build/nginx /etc/nginx/conf.d

ENV PORT 80

EXPOSE 80